import fs from 'node:fs'
import { DatabaseSync, type SQLInputValue } from 'node:sqlite'
import { drizzle, type SqliteRemoteDatabase } from 'drizzle-orm/sqlite-proxy'
import * as schema from './schema'

/**
 * Migrations are plain SQL generated by drizzle-kit (`npm run db:generate`) and bundled
 * into the main process, so nothing has to be shipped beside the executable.
 */
const migrationFiles = import.meta.glob('./migrations/*.sql', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

const migrations = Object.entries(migrationFiles)
  .map(([path, sql]) => ({ name: path.split('/').pop()!.replace(/\.sql$/, ''), sql }))
  .sort((a, b) => a.name.localeCompare(b.name))

export const KNOWN_MIGRATIONS = new Set(migrations.map((m) => m.name))

export type Db = SqliteRemoteDatabase<typeof schema>

let sqlite: DatabaseSync | null = null
let db: Db | null = null
let dbPath = ''

export function runMigrations(conn: DatabaseSync): void {
  conn.exec('CREATE TABLE IF NOT EXISTS __migrations (name TEXT PRIMARY KEY NOT NULL, applied_at TEXT NOT NULL)')
  const applied = new Set(
    (conn.prepare('SELECT name FROM __migrations').all() as { name: string }[]).map((r) => r.name),
  )
  for (const m of migrations) {
    if (applied.has(m.name)) continue
    conn.exec('BEGIN')
    try {
      conn.exec(m.sql)
      conn.prepare('INSERT INTO __migrations (name, applied_at) VALUES (?, ?)').run(m.name, new Date().toISOString())
      conn.exec('COMMIT')
    } catch (err) {
      conn.exec('ROLLBACK')
      throw err
    }
  }
}

export function openDatabase(file: string): void {
  closeDatabase()
  const conn = new DatabaseSync(file)
  conn.exec('PRAGMA foreign_keys = ON')
  runMigrations(conn)
  sqlite = conn
  dbPath = file
  db = drizzle<typeof schema>(
    async (sql, params, method) => {
      const stmt = conn.prepare(sql)
      const args = params as SQLInputValue[]
      if (method === 'run') {
        stmt.run(...args)
        return { rows: [] }
      }
      stmt.setReturnArrays(true)
      const rows = stmt.all(...args) as unknown as unknown[][]
      // drizzle expects the bare row array for "get" and an array of row arrays otherwise
      return { rows: method === 'get' ? (rows[0] as unknown[]) : rows }
    },
    { schema },
  )
}

export function closeDatabase(): void {
  sqlite?.close()
  sqlite = null
  db = null
}

export function getDb(): Db {
  if (!db) throw new Error('Database is not open')
  return db
}

export function getSqlite(): DatabaseSync {
  if (!sqlite) throw new Error('Database is not open')
  return sqlite
}

export function getDatabasePath(): string {
  return dbPath
}

const REQUIRED_COLUMNS: Record<string, string[]> = {
  projects: ['id', 'name', 'description', 'status', 'priority', 'created_at', 'updated_at', 'archived_at'],
  tasks: [
    'id', 'project_id', 'parent_task_id', 'title', 'description', 'status', 'priority',
    'due_date', 'created_at', 'updated_at', 'completed_at',
  ],
}

/** Returns null if `file` is a healthy SprintLane database this version can use, else a reason. */
export function validateSprintLaneDatabase(file: string): string | null {
  let header: Buffer
  try {
    const fd = fs.openSync(file, 'r')
    header = Buffer.alloc(16)
    fs.readSync(fd, header, 0, 16, 0)
    fs.closeSync(fd)
  } catch {
    return 'The selected file could not be read.'
  }
  if (header.toString('latin1', 0, 15) !== 'SQLite format 3') return 'The selected file is not a SQLite database.'

  let conn: DatabaseSync | null = null
  try {
    conn = new DatabaseSync(file, { readOnly: true })
    const check = conn.prepare('PRAGMA quick_check').get() as { quick_check: string } | undefined
    if (check?.quick_check !== 'ok') return 'The database file is corrupted.'

    for (const [table, cols] of Object.entries(REQUIRED_COLUMNS)) {
      const found = (conn.prepare(`PRAGMA table_info(${table})`).all() as { name: string }[]).map((c) => c.name)
      if (found.length === 0 || cols.some((c) => !found.includes(c))) {
        return 'The selected file is not a SprintLane database.'
      }
    }
    const hasMigrations = conn
      .prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = '__migrations'")
      .get()
    if (!hasMigrations) return 'The selected file is not a SprintLane database.'
    const names = (conn.prepare('SELECT name FROM __migrations').all() as { name: string }[]).map((r) => r.name)
    if (names.some((n) => !KNOWN_MIGRATIONS.has(n))) {
      return 'This backup was created by a newer version of SprintLane. Please update the app first.'
    }
    return null
  } catch {
    return 'The selected file is not a valid SprintLane database.'
  } finally {
    conn?.close()
  }
}
